CREATE ROLE creator WITH LOGIN;
ALTER USER creator WITH PASSWORD 'password';


CREATE ROLE reader WITH LOGIN PASSWORD 'password'
    NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION VALID UNTIL 'infinity';

GRANT CONNECT ON DATABASE sensors TO reader;
GRANT USAGE ON SCHEMA sensors TO reader;
GRANT SELECT ON ALL TABLES IN SCHEMA sensors TO reader;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA sensors TO reader;
ALTER DEFAULT PRIVILEGES IN SCHEMA sensors GRANT SELECT ON TABLES TO reader;
